CapstoneAOZTG/greengrim-server

- green/src/main/java/com/greengrim/green/core/testMember/TestMemberController.java
- green/src/main/java/com/greengrim/green/core/testMember/TestMemberRepository.java
- green/src/main/java/com/greengrim/green/core/testMember/TestMemberService.java
Closes #1 
<br><br>
- 테스트 멤버 삭제 코드 작성으로 PR 테스트
> test: [#1] 테스트 멤버 삭제 작성

- green/src/main/java/com/greengrim/green/core/testMember/TestMember.java
Closes #4
<br><br>
- (가능한 한 자세히 작성해 주시면 감사하겠습니다!)
<br><br>
- (리뷰어에게 부탁하는 말을 작성해주세요. 없다면 지워도 됩니다!)
<br><br>
- (없다면 지워도 됩니다!)
> Feat: TestMember에 description 추가

- green/src/main/java/com/greengrim/green/common/exception/BaseException.java
- green/src/main/java/com/greengrim/green/common/exception/ControllerAdvice.java
- green/src/main/java/com/greengrim/green/common/exception/ErrorCode.java
- green/src/main/java/com/greengrim/green/common/exception/ExceptionResponse.java
- green/src/main/java/com/greengrim/green/common/exception/errorCode/GlobalErrorCode.java
Closes #6 
<br><br>
- `BaseException` : Exception 기본 형태를 정의
- `ExceptionResponse` : Exception 발생 시 클라이언트에게 전달할 Response
- `ControllerAdvice` : 미리 지정해논 Error가 발생했을 시 `ExceptionResponse` 형태로 변환하여 클라이언트에게 전달
- `ErrorCode` : ErrorCode에서 사용할 추상 함수를 담은 인터페이스로, 도메인 별 ErrorCode를 정의할 때 implement 
<br><br>
- `ControllerAdvice`에 `System.out.println(e);` 이라는 코드가 들어가있습니다! 개발 과정에서 편하게 확인하기 위해 추가한 것인데, 추후에 로그로 변경하도록 하겠습니다 ㅜ.ㅜ
- common > exception > errorCode 폴더에 도메인 별로 에러코드를 정의하여 사용하시면 됩니다! 예시로 `GlobalErrorCode`를 만들어놓았으니 참고해주세요!!
<br><br>
> [Feat] Exception 처리 구현

- green/Dockerfile
Closes #12 
서브 모듈 레포의 application.yml 파일 수정
도커 파일 수정
> dev, prod 환경 구분

- green/src/test/java/com/greengrim/green/GreenApplicationTests.java
Closes #12
<br><br>
build를 위해 임시적으로 spring boot test 어노테이션 삭제
> spring boot test 어노테이션 삭제 (임시)

- green/docker/README.md
- green/docker/database-local-m.yml
- green/docker/database-local.yml
Closes #11 
<br><br>
local db용 도커 파일 추가
docker 설치 필요합니다.
> local db용 도커 파일 추가

- .github/workflows/green-grim-deploy.yml
> [env] 서브모듈 재설정

- green/build.gradle
- green/src/main/java/com/greengrim/green/common/auth/CurrentMember.java
- green/src/main/java/com/greengrim/green/common/auth/CustomAccessDeniedHandler.java
- green/src/main/java/com/greengrim/green/common/auth/PrincipalDetails.java
- green/src/main/java/com/greengrim/green/common/auth/PrincipalDetailsService.java
- green/src/main/java/com/greengrim/green/common/config/SecurityConfig.java
- green/src/main/java/com/greengrim/green/common/entity/BaseTime.java
- green/src/main/java/com/greengrim/green/common/exception/errorCode/AuthErrorCode.java
- green/src/main/java/com/greengrim/green/common/exception/errorCode/MemberErrorCode.java
- green/src/main/java/com/greengrim/green/common/jwt/JwtAuthenticationFilter.java
- green/src/main/java/com/greengrim/green/common/jwt/JwtExceptionFilter.java
- green/src/main/java/com/greengrim/green/common/jwt/JwtTokenProvider.java
- green/src/main/java/com/greengrim/green/core/member/Member.java
- green/src/main/java/com/greengrim/green/core/member/Role.java
- green/src/main/java/com/greengrim/green/core/member/controller/RegisterMemberController.java
- green/src/main/java/com/greengrim/green/core/member/dto/MemberRequestDto.java
- green/src/main/java/com/greengrim/green/core/member/dto/MemberResponseDto.java
- green/src/main/java/com/greengrim/green/core/member/repository/MemberRepository.java
- green/src/main/java/com/greengrim/green/core/member/service/RegisterMemberService.java
- green/src/main/java/com/greengrim/green/core/member/usecase/RegisterMemberUseCase.java
#8 , Closes #10 
- 1개의 도메인에 대해 `entity`, `controller`, `service`, `usecase`, `repository`, `dto` 로 디렉토리 및 역할 분할  
- `controller`, `service`, `usecase` 는 `Register`, `Update`, `Get` 으로 다시 역할 분할
ex) `RegisterMemberController`, `GetMemberController` 등
- 인터페이스인 `usecase`는 `service`에 있는 함수들의 선언을 모아논 것입니다. `usecase`를 `service`가 `implements` 하도록 하면 됩니다!
→ 서로 다른 파트를 구현하므로 함수의 내부 동작을 자세히 모르더라도 `usecase`의 네이밍, 파라미터만 보고 바로 사용할 수 있게 됩니다.
→ 따라서 `usecase` 함수 명과 파라미터만 보고 기능을 파악할 수 있도록 네이밍을 지어야합니다.
1. 사용자가 로그인 정보와 함께 인증 요청을 한다. (Http Request)
2. `JwtAuthenticationFilter`가 요청을 가로채고, 가로챈 정보를 `JwtTokenProvider`에 넘겨 토큰이 유효한지 확인한다.
3. 토큰이 유효하다면 토큰으로부터 사용자 정보(`memberId`)를 추출한다.
4. 실제 DB에서 사용자 인증정보를 가져오는 `PrincipalDetailsService`에 사용자 정보(`memberId`)를 넘겨준다.
6. 넘겨받은 사용자 정보(`memberId`)를 통해 DB에서 찾은 사용자 정보(`member …
> JWT 및 Spring Security 세팅 & 회원 가입 API 구현

- green/build.gradle
- green/src/main/java/com/greengrim/green/common/auth/PrincipalDetails.java
- green/src/main/java/com/greengrim/green/core/member/Member.java
- green/src/main/java/com/greengrim/green/core/member/service/RegisterMemberService.java
Closes #10
<br><br>
- jwt 생성 중 에러 발생 -> 아래 dependency 추가
```
dependencies {
implementation 'io.jsonwebtoken:jjwt:0.9.1'
// com.sun.xml.bind
implementation 'com.sun.xml.bind:jaxb-impl:4.0.1'
implementation 'com.sun.xml.bind:jaxb-core:4.0.1'
// javax.xml.bind
implementation 'javax.xml.bind:jaxb-api:2.4.0-b180830.0359'
}
```
- https://velog.io/@kon6443/Error-log-Spring-Boot-JWT-%EC%83%9D%EC%84%B1-javaxxmlbindDatatypeConverter-%EC%97%90%EB%9F%AC
> JWT 종속성 추가 및 Member Entity 생성 방법 변경

- green/build.gradle
- green/src/main/java/com/greengrim/green/common/s3/S3Config.java
- green/src/main/java/com/greengrim/green/common/s3/S3Controller.java
- green/src/main/java/com/greengrim/green/common/s3/S3Service.java
- green/src/main/java/com/greengrim/green/common/s3/dto/S3Result.java
Closes #33
<br><br>
- S3 관련디렉토리 추가
- S3Config
- S3Controller
- S3Service
- S3Result (DTO)
- S3 파일 업로드 API 구현
- MultipartFile로 업로드하면 S3에 저장하고 URL 반환 
<br><br>
- [(없다면 지워도 됩니다!)](https://gaeggu.tistory.com/33)
> AWS S3 설정과 S3 파일 업로드 API

- green/src/main/java/com/greengrim/green/GreenApplication.java
- green/src/main/java/com/greengrim/green/common/entity/BaseTime.java
- green/src/main/java/com/greengrim/green/common/s3/S3Service.java
- green/src/main/java/com/greengrim/green/core/member/Member.java
- green/src/main/java/com/greengrim/green/core/member/controller/GetMemberController.java
- green/src/main/java/com/greengrim/green/core/member/controller/UpdateMemberController.java
- green/src/main/java/com/greengrim/green/core/member/dto/MemberRequestDto.java
- green/src/main/java/com/greengrim/green/core/member/dto/MemberResponseDto.java
- green/src/main/java/com/greengrim/green/core/member/service/GetMemberService.java
- green/src/main/java/com/greengrim/green/core/member/service/RegisterMemberService.java
- green/src/main/java/com/greengrim/green/core/member/service/UpdateMemberService.java
- green/src/main/java/com/greengrim/green/core/member/usecase/GetMemberUseCase.java
- green/src/main/java/com/greengrim/green/core/member/usecase/UpdateMemberUseCase.java
Closes #29
<br><br>
- 프로필 이미지 업로드 및 삭제를 위한 S3 설정 
- 내 프로필 조회 API
- 내 프로필 수정 API
- 회원 탈퇴 API
<br><br>
> 로그인 및 회원 관련 API 2

- green/src/main/java/com/greengrim/green/common/config/RedisConfig.java
- green/src/main/java/com/greengrim/green/common/handler/StompHandler.java
- green/src/main/java/com/greengrim/green/core/chat/ChatController.java
- green/src/main/java/com/greengrim/green/core/chat/ChatService.java
- green/src/main/java/com/greengrim/green/core/chat/dto/ChatMessage.java
- green/src/main/java/com/greengrim/green/core/chatRoom/ChatRoom.java
- green/src/main/java/com/greengrim/green/core/chatRoom/ChatRoomController.java
- green/src/main/java/com/greengrim/green/core/chatRoom/ChatRoomRepository.java
Closes #
<br><br>
- 채팅 기능 중 입퇴장 이벤트, 인원 수 처리 적용 테스트 PR입니다.  #32 와 같은 이유로  혹시나 수정 사항이 있을 시 PR을 열지 않고 로컬 - develop으로 push할 예정입니다.
> 채팅- 입퇴장 이벤트, 인원 수 처리

- green/src/main/java/com/greengrim/green/core/certification/controller/RegisterCertificationController.java
- green/src/main/java/com/greengrim/green/core/certification/dto/CertificationRequestDto.java
- green/src/main/java/com/greengrim/green/core/certification/dto/CertificationResponseDto.java
- green/src/main/java/com/greengrim/green/core/certification/repository/CertificationRepository.java
- green/src/main/java/com/greengrim/green/core/certification/service/RegisterCertificationService.java
- green/src/main/java/com/greengrim/green/core/challenge/controller/GetChallengeController.java
- green/src/main/java/com/greengrim/green/core/challenge/dto/ChallengeResponseDto.java
- green/src/main/java/com/greengrim/green/core/challenge/repository/ChallengeRepository.java
- green/src/main/java/com/greengrim/green/core/challenge/service/GetChallengeService.java
#8 
<br><br>
- [Feat: 홈 화면 핫 챌린지 조회 API](https://github.com/CapstoneAOZTG/greengrim-server/commit/01f4a35b4dd45db120636e4ab7d4e09adb9e488b) 
- 조건: 진행 중, 참여 인원 많은, 최신순
- [Feat: 핫 챌린지 더보기 API](https://github.com/CapstoneAOZTG/greengrim-server/commit/6e9f160766605903d7a026e3e2d7e3d9e266c1da) 
- [Feat: 챌린지 인증하기 API](https://github.com/CapstoneAOZTG/greengrim-server/commit/22b53e53a6ef691377e46be04746edcd3926a644)
<br><br>
- (리뷰어에게 부탁하는 말을 작성해주세요. 없다면 지워도 됩니다!)
<br><br>
- (없다면 지워도 됩니다!)
> 홈화면 챌린지 조회 API & 챌린지 인증하기 API

- green/src/main/java/com/greengrim/green/common/entity/SortOption.java
- green/src/main/java/com/greengrim/green/core/challenge/controller/GetChallengeController.java
- green/src/main/java/com/greengrim/green/core/challenge/service/GetChallengeService.java
#8
<br><br>
- 챌린지 목록 조회 API 페이징 수정
<br><br>
> 챌린지 목록 조회 API 페이징 수정

- green/src/main/java/com/greengrim/green/core/challenge/repository/ChallengeRepository.java
- green/src/main/java/com/greengrim/green/core/challenge/service/GetChallengeService.java
> 챌린지 페이징 수정

- green/src/main/java/com/greengrim/green/core/challenge/controller/EnterChallengeController.java
- green/src/main/java/com/greengrim/green/core/chat/ChatMessage.java
- green/src/main/java/com/greengrim/green/core/chat/controller/ChatController.java
- green/src/main/java/com/greengrim/green/core/chat/service/ChatService.java
- green/src/main/java/com/greengrim/green/core/chatroom/controller/ChatroomController.java
- green/src/main/java/com/greengrim/green/core/chatroom/service/ChatroomService.java
- green/src/main/java/com/greengrim/green/core/member/service/GetMemberService.java
- green/src/main/java/com/greengrim/green/core/member/usecase/GetMemberUseCase.java
Closes #
<br><br>
-  메세지 Entity 수정
-  메세지 전송 API 수정
-  내가 속한 챌린지-채팅방을 주는 API 추가
> 메세지 타입 수정 - 채팅 리팩토링

- green/src/main/java/com/greengrim/green/core/certification/service/GetCertificationService.java
- green/src/main/java/com/greengrim/green/core/verification/VerificationService.java
Closes #8
<br><br>
- GetCertificationService와 VerificationService 간 순환참조를 해결했습니다
<br><br>
- (리뷰어에게 부탁하는 말을 작성해주세요. 없다면 지워도 됩니다!)
<br><br>
- (없다면 지워도 됩니다!)
> Service 간 순환참조 해결

- green/src/main/java/com/greengrim/green/common/exception/errorCode/VerificationErrorCode.java
- green/src/main/java/com/greengrim/green/core/certification/controller/GetCertificationController.java
- green/src/main/java/com/greengrim/green/core/certification/repository/CertificationRepository.java
- green/src/main/java/com/greengrim/green/core/certification/service/GetCertificationService.java
- green/src/main/java/com/greengrim/green/core/verification/VerificationService.java
- [Feat: 출석체크 할 인증 조회 API](https://github.com/CapstoneAOZTG/greengrim-server/commit/550f37e455c1d4fa51514e4b3a856b772ce2a83b)
- [Feat: 출석체크 답변 제출 API 예외 처리 추가](https://github.com/CapstoneAOZTG/greengrim-server/commit/256d314fd035433275ac2fe473a1d2c0611fddff)
- 이미 참여한 출석체크일 경우 예외 발생
- 자신의 인증에 대해 출석체크 하려고 할 경우 예외 발생
> 출석체크 관련 API

- green/build.gradle
- green/src/main/java/com/greengrim/green/common/exception/errorCode/WalletErrorCode.java
- green/src/main/java/com/greengrim/green/common/kas/KasConstants.java
- green/src/main/java/com/greengrim/green/common/kas/KasProperties.java
- green/src/main/java/com/greengrim/green/common/kas/KasService.java
- green/src/main/java/com/greengrim/green/common/password/BcryptService.java
- green/src/main/java/com/greengrim/green/core/certification/controller/GetCertificationController.java
- green/src/main/java/com/greengrim/green/core/certification/repository/CertificationRepository.java
- green/src/main/java/com/greengrim/green/core/certification/service/GetCertificationService.java
- green/src/main/java/com/greengrim/green/core/member/Member.java
- green/src/main/java/com/greengrim/green/core/transaction/Transaction.java
- green/src/main/java/com/greengrim/green/core/transaction/dto/TransactionRequestDto.java
- green/src/main/java/com/greengrim/green/core/verification/VerificationController.java
- green/src/main/java/com/greengrim/green/core/verification/VerificationService.java
- green/src/main/java/com/greengrim/green/core/verification/dto/VerificationRequestDto.java
- green/src/main/java/com/greengrim/green/core/wallet/Wallet.java
- green/src/main/java/com/greengrim/green/core/wallet/WalletController.java
- green/src/main/java/com/greengrim/green/core/wallet/WalletRepository.java
- green/src/main/java/com/greengrim/green/core/wallet/WalletService.java
- green/src/main/java/com/greengrim/green/core/wallet/controller/WalletController.java
- green/src/main/java/com/greengrim/green/core/wallet/controller/WalletPasswordController.java
- green/src/main/java/com/greengrim/green/core/wallet/dto/WalletRequestDto.java
- green/src/main/java/com/greengrim/green/core/wallet/dto/WalletResponseDto.java
- green/src/main/java/com/greengrim/green/core/wallet/repository/WalletRepository.java
- green/src/main/java/com/greengrim/green/core/wallet/service/WalletPasswordService.java
- green/src/main/java/com/greengrim/green/core/wallet/service/WalletService.java
Closes #8
- [Feat: 지갑 발급하기 & 비밀번호 확인하기 API](https://github.com/CapstoneAOZTG/greengrim-server/commit/c7878ebe2b8cb0b1645a1e3e66095b737c526b5a)
- [Feat: 월 별 인증 조회하기 response 변경](https://github.com/CapstoneAOZTG/greengrim-server/commit/f94f87f2ee660fe296cc5b47cfd18f89fd3541a7)
> 지갑 생성 API, 비밀번호 확인 API, 월 별 인증 조회 API 수정

- green/src/main/java/com/greengrim/green/core/chat/repository/ChatRepository.java
> refactor: [#155] 오타 수정
